<div class="container-fluid">
    <div>
        <h3>E-mail & SMS Setup</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Settings</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">E-mail & SMS Setup</li>
            </ol>
        </nav>
    </div>
    <div class="alert alert-info">
       <i class="fa fa-fw fa-exclamation-triangle"></i> <strong>Info: </strong> Fیا اطلاعات بیشتر در مورد نحوه راه اندازی سرور ایمیل یا ارائه دهندگان پیامک، لطفاً به ما مراجعه کنید <a href="https://docs.wowonder.com/#idocs_smtp" target="_blank">Documentation</a> page.
   </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">پیکربندی ایمیل</h6>
                    <form class="email-settings" method="POST">
                        <label for="smtp_or_mail" class="main-label">سرور ایمیل</label>
                        <select class="form-control show-tick" id="smtp_or_mail" name="smtp_or_mail">
                          <option value="smtp" <?php if($wo['config']['smtp_or_mail'] == 'smtp'){echo 'selected';};?> >سرور SMTP</option>
                          <option value="mail" <?php if($wo['config']['smtp_or_mail'] == 'mail'){echo 'selected';};?> >ایمیل سرور (پیش‌فرض)</option>
                        </select>
                        <small class="admin-info">از کدام سرور ایمیل می خواهید استفاده کنید، عملکرد ایمیل سرور توصیه نمی شود.</small>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">ایمیل پیش فرض وب سایت</label>
                                <input type="text" id="siteEmail" name="siteEmail" class="form-control" value="<?php echo $wo['config']['siteEmail']; ?>">
                                <small class="admin-info">این ایمیل پیش فرض وب سایت شما است، از این ایمیل برای ارسال ایمیل به کاربران استفاده می شود.</small>
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">میزبان SMTP</label>
                                <input type="text" id="smtp_host" name="smtp_host" class="form-control" value="<?php echo $wo['config']['smtp_host'];?>">
                                <small class="admin-info">نام میزبان حساب SMTP شما می تواند IP، دامنه یا ساب دامنه باشد.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">نام کاربری SMTP</label>
                                <input type="text" id="smtp_username" name="smtp_username" class="form-control" value="<?php echo $wo['config']['smtp_username'];?>">
                                <small class="admin-info">نام کاربری حساب SMTP شما.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">رمز عبور SMTP</label>
                                <input type="password" id="smtp_password" name="smtp_password" class="form-control" value="<?php echo openssl_decrypt($wo['config']['smtp_password'], "AES-128-ECB", 'mysecretkey1234');?>">
                                <small class="admin-info">رمز عبور حساب SMTP شما</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">پورت SMTP</label>
                                <input type="text" id="smtp_port" name="smtp_port" class="form-control" value="<?php echo $wo['config']['smtp_port'];?>">
                                <small class="admin-info">سرور SMTP شما از کدام پورت استفاده می کند؟ بیشترین استفاده از 587 برای TLS و 465 برای رمزگذاری SSL. </small>
                            </div>
                        </div>
                        <label for="smtp_encryption">رمزگذاری SMTPn</label>
                        <select class="form-control show-tick" id="smtp_encryption" name="smtp_encryption">
                          <option value="tls" <?php if((strtolower($wo['config']['smtp_encryption']) == 'tls')){echo 'selected';};?> >TLS (پیش‌فرض، ایمن نیست)</option>
                          <option value="ssl" <?php if((strtolower($wo['config']['smtp_encryption']) == 'ssl')){echo 'selected';};?> >SSL (امن)</option>
                        </select>
                        <small class="admin-info">سرور SMTP شما از کدام روش رمزگذاری استفاده می کند؟</small>
                        <div class="clearfix"></div><br>
                        <div class="alert alert-info">
                            پس از کلیک بر روی "تست ایمیل سرور"، یک پیام آزمایشی به آدرس ایمیل حساب شما ارسال می شود.
                        </div>
                        <div class="email-settings-alert"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <!-- <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button> -->
                        <button type="button" class="btn btn-success m-t-15 waves-effect" onclick="Wo_TestMessage();">تست سرویس ایمیلr</button>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">تنظیمات پیامک</h6>

                    <form class="sms-settings" method="POST">
                        <div class="alert alert-info">برای شروع ارسال پیامک، باید یک حساب کاربری ایجاد کرده و اعتبار خریداری کنید <a href="http://www.twilio.com">Twilio</a> <span class="red">OR</span> <a href="http://www.bulksms.com/">BulkSMS</a> <span class="red">OR</span> <a href="https://www.infobip.com/">Infobip</a>.</div><br>

                        <label for="sms_provider" class="main-label">ارائه دهنده پیش فرض پیامک</label>
                        <select class="form-control show-tick" id="sms_provider" name="sms_provider">
                          <option value="twilio" <?php if($wo['config']['sms_provider'] == 'twilio'){echo 'selected';};?> >Twilio</option>
                          <option value="bulksms" <?php if($wo['config']['sms_provider'] == 'bulksms'){echo 'selected';};?> >BulkSMS</option>
                          <option value="infobip" <?php if($wo['config']['sms_provider'] == 'infobip'){echo 'selected';};?> >Infobip</option>
                          <option value="msg91" <?php if($wo['config']['sms_provider'] == 'msg91'){echo 'selected';};?> >Msg91</option>
                        </select>
                        <small class="admin-info">انتخاب کنید که از کدام ارائه دهنده پیامک می خواهید استفاده کنید، می توانید همزمان فقط از یکی استفاده کنید.</small>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">شماره تلفن شما</label>
                                <input type="text" id="sms_phone_number" name="sms_phone_number" class="form-control" value="<?php echo $wo['config']['sms_phone_number'];?>">
                                <small class="admin-info">شماره پیش‌فرض وب‌سایت خود را تنظیم کنید، از این شماره برای ارسال پیامک به کاربران استفاده می‌شود، به عنوان مثال (+9053..)</small>
                            </div>
                        </div>
                        <hr>
                        <label  class="main-label">پیکربندی BulkSMS</label><br><br>
                        <!-- <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">BulkSMS Eapi_URL</label>
                                <input type="text" id="eapi" name="eapi" class="form-control" value="<?php echo $wo['config']['eapi'];?>">
                            </div>
                        </div> -->
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">نام کاربری BulkSMS</label>
                                <input type="text" id="sms_username" name="sms_username" class="form-control" value="<?php echo $wo['config']['sms_username'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">رمز عبور انبوه اس ام اس</label>
                                <input type="password" id="sms_password" name="sms_password" class="form-control" value="<?php echo $wo['config']['sms_password'];?>">
                            </div>
                        </div>
                       <hr>
                       <label  class="main-label">پیکربندی Twilio</label><br><br>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Twilio account_sid</label>
                                <input type="text" id="sms_twilio_username" name="sms_twilio_username" class="form-control" value="<?php echo $wo['config']['sms_twilio_username'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Twilio auth_token</label>
                                <input type="text" id="sms_twilio_password" name="sms_twilio_password" class="form-control" value="<?php echo $wo['config']['sms_twilio_password'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Twilio Phone number</label>
                                <input type="text" id="sms_t_phone_number" name="sms_t_phone_number" class="form-control" value="<?php echo $wo['config']['sms_t_phone_number'];?>">
                            </div>
                        </div>
                        <hr>
                        <label  class="main-label">Infobip Configuration</label><br><br>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Infobip API Key</label>
                                <input type="text" id="infobip_api_key" name="infobip_api_key" class="form-control" value="<?php echo $wo['config']['infobip_api_key'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Infobip Base URL</label>
                                <input type="text" id="infobip_base_url" name="infobip_base_url" class="form-control" value="<?php echo $wo['config']['infobip_base_url'];?>">
                            </div>
                        </div>
                        <hr>
                        <label  class="main-label">Msg91 Configuration</label><br><br>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Msg91 AuthKey</label>
                                <input type="text" id="msg91_authKey" name="msg91_authKey" class="form-control" value="<?php echo $wo['config']['msg91_authKey'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Msg91 DLT ID</label>
                                <input type="text" id="msg91_dlt_id" name="msg91_dlt_id" class="form-control" value="<?php echo $wo['config']['msg91_dlt_id'];?>">
                            </div>
                        </div>


                        <div class="alert alert-info">After clicking "Test SMS Server", a test message will be sent to your phone</div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <div class="sms-settings-alert"></div>
                        <!-- <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button> -->
                        <button type="button" class="btn btn-success m-t-15 waves-effect" onclick="Wo_TestSMSMessage();">Test SMS Server</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">اشکال زدایی ایمیل تحویل</h6>
                    <div class="alert alert-info">این ویژگی قابلیت تحویل ایمیل را آزمایش می کند و مطمئن می شود که سیستم به خوبی کار می کند.</div>
                    <form class="debug-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">گزارش اشکال زدایی</label>
                                <textarea name="debug_email" id="debug_email" class="form-control" cols="30" rows="5" style="height: 700px !important;" disabled>برای نمایش نتایج آزمایش، روی Debug Email Deliverability کلیک کنید.</textarea>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <div class="debug-settings-alert"></div>
                        <button type="submit" class="btn btn-success m-t-15 waves-effect">اشکال زدایی ایمیل تحویل</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
function Wo_TestMessage() {
    $('form.email-settings').find('.btn-success').text('Please wait..');
    $.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'test_message'}, function (data) {
        if (data.status == 200) {
            $('.email-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Message sent!</div>');
            setTimeout(function () {
                $('.email-settings-alert').empty();
            }, 2000);
        } else {
            $('.email-settings-alert').html('<div class="alert alert-danger">Message failed to sent, error: ' + data.error+'</div>');
            setTimeout(function () {
                $('.email-settings-alert').empty();
            }, 2000);
        }
        $('form.email-settings').find('.btn-success').text('Test E-mail Server');
    });
}
function Wo_TestSMSMessage() {
    $('form.sms-settings').find('.btn-success').text('Please wait..');
    $.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'test_sms_message'}, function (data) {
        if (data.status == 200) {
            $('.sms-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Message sent!</div>');
            setTimeout(function () {
                $('.sms-settings-alert').empty();
            }, 2000);
        } else {
            $('.sms-settings-alert').html('<div class="alert alert-danger">Message failed to sent, error: ' + data.error+'</div>');
            setTimeout(function () {
                $('.sms-settings-alert').empty();
            }, 2000);
        }
        $('form.sms-settings').find('.btn-success').text('Test SMS Server');
    });
}
$(function() {
    var debug_settings = $('form.debug-settings');
    debug_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=email_debug',
        beforeSend: function() {
            debug_settings.find('.waves-effect').text("Please wait..");
        },
        success: function(data) {
            debug_settings.find('.waves-effect').text('Debug');
            $('#debug_email').val(data);
        },
        error: function(data) {
            debug_settings.find('.waves-effect').text('Debug');
            $('#debug_email').val(data.responseText);
        }
    });

    $('.switcher input[type=checkbox]').click(function () {
        setToTrue = 0;
        if ($(this).is(":checked") === true) {
            setToTrue = 1;
        }
        var configName = $(this).attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = setToTrue;
        objData['hash_id'] = hash_id;
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData);
    });

    var setTimeOutColor = setTimeout(function (){});
    $('select').on('change', function() {
         clearTimeout(setTimeOutColor);
        var thisElement = $(this);
        var configName = thisElement.attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = this.value;
        objData['hash_id'] = hash_id;
        thisElement.addClass('warning');
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
            if (data.status == 200) {
                thisElement.removeClass('warning');
                thisElement.addClass('success');
            } else {
                thisElement.addClass('error');
            }
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('success');
                thisElement.removeClass('warning');
                thisElement.removeClass('error');
            }, 2000);
        });
    });
    $('input[type=text], input[type=number], input[type=password]').on('input', delay(function() {
            clearTimeout(setTimeOutColor);
            var thisElement = $(this);
            var configName = thisElement.attr('name');
            var hash_id = $('input[name=hash_id]').val();
            var objData = {};
            objData[configName] = this.value;
            objData['hash_id'] = hash_id;
            thisElement.addClass('warning');
            $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
                if (data.status == 200) {
                    thisElement.removeClass('warning');
                    thisElement.addClass('success');
                } else {
                    thisElement.addClass('error');
                }
                var setTimeOutColor = setTimeout(function () {
                    thisElement.removeClass('success');
                    thisElement.removeClass('warning');
                    thisElement.removeClass('error');
                }, 2000);
                //thisElement.focus();
            });
    }, 500));
});
</script>
